name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - run: uv sync
      shell: bash
